server:
  http2:
    enabled: true
  error:
    include-stacktrace: always
    include-message: always
spring.jpa:
  database: oracle
  show-sql: true
spring.datasource:
  platform: oracle
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:postgresql://172.16.17.65:5432/etp
  username: websecuirty
  password: wbs123t4
